
export const data = [
  {
    id: "glossId1",
    title: "Knowledge center",
    owner: "Udit",
    createdAt: "Mon Dec 09 2024 00:00:00 GMT+0530 (India Standard Time)",
    status: "published",
    collaborators: [],
    pages: [
      {
        id: "glossId1_page1",
        title: "Seven wonders of the world",
        content: "<h1>Hello my romans, country men</h1><p>this is sparta</p>",
        status: "draft",
        createdAt: "Mon Dec 09 2024 00:00:00 GMT+0530 (India Standard Time)",
        updatedAt: "Mon Dec 09 2024 00:00:00 GMT+0530 (India Standard Time)",
        collaborators: [],
        status: "draft",
        attachments: [],
        version: "1.1",
      },
      {
        id: "glossId13_page112",
        title: "Snakes defintions",
        content: "<h1>Snakes are dangerous to all other animals</h1>",
        status: "draft",
        createdAt: "Mon Dec 09 2024 00:00:00 GMT+0530 (India Standard Time)",
        updatedAt: "Mon Dec 09 2024 00:00:00 GMT+0530 (India Standard Time)",
        collaborators: [],
        status: "draft",
        attachments: [],
        version: "1.1",
      },
      {
        id: "glossId1_page2",
        title: "Machu pichu and all others in Latin America",
        content: "<h1>Hello my machu pichu, country men</h1><p>this is machu pichu</p>",
        status: "draft",
        createdAt: "Mon Dec 09 2024 00:00:00 GMT+0530 (India Standard Time)",
        updatedAt: "Mon Dec 09 2024 00:00:00 GMT+0530 (India Standard Time)",
        collaborators: [],
        status: "draft",
        attachments: [],
        version: "1.1",
      },
      {
        id: "glossId121_page232",
        title: "Maginficiant Century",
        content: "<h1>Hello my machu magnificient century, country men</h1><p>this is ,amgsa</p>",
        status: "draft",
        createdAt: "Mon Dec 09 2024 00:00:00 GMT+0530 (India Standard Time)",
        updatedAt: "Mon Dec 09 2024 00:00:00 GMT+0530 (India Standard Time)",
        collaborators: [],
        status: "draft",
        attachments: [],
        version: "1.1",
      },
    ],
  },
  {
    id: "glossId2",
    title: "Knowledge center 2",
    owner: "Udit",
    createdAt: "Mon Dec 09 2024 00:00:00 GMT+0530 (India Standard Time)",
    status: "draft",
    collaborators: [],
    pages: [],
  },
  {
    id: "glossId3",
    title: "My published book center",
    owner: "Udit",
    createdAt: "Mon Dec 09 2024 00:00:00 GMT+0530 (India Standard Time)",
    status: "draft",
    collaborators: [],
    pages: [],
  },
  {
    id: "glossId4",
    title: "Knowledge center 3",
    owner: "Udit",
    createdAt: "Mon Dec 09 2024 00:00:00 GMT+0530 (India Standard Time)",
    status: "shared",
    collaborators: [],
    pages: [
      {
        id: "glossId4_page1",
        title: "Art Seven wonders of the world",
        content: "hello verf j r ",
        status: "draft",
        createdAt: "Mon Dec 09 2024 00:00:00 GMT+0530 (India Standard Time)",
        updatedAt: "Mon Dec 09 2024 00:00:00 GMT+0530 (India Standard Time)",
        collaborators: [],
        status: "shared",
        attachments: [],
        version: "1.1",
      },
      {
        id: "glossId4_page2",
        title: "Sr Machu pichu",
        content: "rvf rvfvvfv fv",
        status: "draft",
        createdAt: "Mon Dec 09 2024 00:00:00 GMT+0530 (India Standard Time)",
        updatedAt: "Mon Dec 09 2024 00:00:00 GMT+0530 (India Standard Time)",
        collaborators: [],
        status: "shared",
        attachments: [],
        version: "1.1",
      },
      {
        id: "glossId4_page2",
        title: "H Sr Machu pichu",
        content: "rvf v  vfdrvfvvfv fv",
        status: "draft",
        createdAt: "Mon Dec 09 2024 00:00:00 GMT+0530 (India Standard Time)",
        updatedAt: "Mon Dec 09 2024 00:00:00 GMT+0530 (India Standard Time)",
        collaborators: [],
        status: "shared",
        attachments: [],
        version: "1.1",
      },
    ],
  },
];

